language: python
services:
  - xvfb
python:
  - 3.6
before_install:
  - export DISPLAY=:99
install:
  - pip install -r test-requirements.txt
  - pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/base.txt
  - pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/test.txt
  - pip install -r $VIRTUAL_ENV/src/xblock/requirements.txt
script:
  - pep8 --max-line-length=100 vectordraw
  - pylint vectordraw
  - ./run_tests.py --with-coverage --cover-package=vectordraw
notifications:
  email: false
addons:
  firefox: 36.0
